import logging

logger = logging.getLogger(__name__)

# Generated by Django 6.0.1 on 2026-01-27 09:40

from django.db import migrations, models


# Summary: Определяет операции миграции базы данных для этого модуля.
class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
    ]
