import logging

logger = logging.getLogger(__name__)

# Generated by Django 5.2.7 on 2026-02-05 07:25

import django.db.models.deletion
from django.db import migrations, models


# Summary: Определяет операции миграции базы данных для этого модуля.
class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_manager_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerprojectnotification',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='EmployeeProjectAssignmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'db_table': 'employee_project_assignment_notifications',
                'managed': True,
            },
        ),
    ]
