import logging

logger = logging.getLogger(__name__)

# Generated by Django 6.0.1 on 2026-03-05 07:38

import django.db.models.deletion
from django.db import migrations, models


# Summary: Определяет операции миграции базы данных для этого модуля.
class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_projectchatmessage_projectchatattachment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeTaskAssignmentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.projecttask",
                    ),
                ),
            ],
            options={
                "db_table": "employee_task_assignment_notifications",
                "managed": True,
                "unique_together": {("employee", "task")},
            },
        ),
    ]
