import logging

logger = logging.getLogger(__name__)

# Generated by Django 6.0.1 on 2026-03-05 07:38

from django.db import migrations, models
import django.db.models.deletion


# Summary: Определяет операции миграции базы данных для этого модуля.
class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_employeetaskassignmentnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='core.employee'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(blank=True, default='в работе', max_length=20, null=True),
        ),
    ]
