import logging

logger = logging.getLogger(__name__)

# Generated by Django 6.0.1 on 2026-04-04 06:26

from django.db import migrations


# Summary: Определяет операции миграции базы данных для этого модуля.
class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_taskattachment"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE employees ADD COLUMN force_password_change BOOLEAN DEFAULT TRUE;",
            reverse_sql="ALTER TABLE employees DROP COLUMN force_password_change;"
        )
    ]
